---

# "zellij" version to install
zellij_version: "0.38.2"
zellij_bin_path: "/usr/local/bin"
zellij_tmp_directory: "{{ lookup('env', 'TMPDIR') | default('/tmp', true) }}"
zellij_os: "unknown-linux-musl"
zellij_arch: "x86_64"
